name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

# 强制禁用 Node.js 20 警告
env:
  ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Download FFmpeg Dev
        run: |
          curl -L "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-dev.zip" -o ffmpeg-dev.zip
          unzip ffmpeg-dev.zip
          mv ffmpeg-n7.1-latest-win64-gpl-dev ffmpeg
        shell: bash

      - name: Compile EXE
        run: |
          gcc -o rtsp_record.exe rtsp_record.c \
          -I./ffmpeg/include \
          -L./ffmpeg/lib \
          -lavformat -lavcodec -lavutil -lws2_32
        shell: bash

      - name: Download FFmpeg Shared DLLs
        run: |
          curl -L "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-shared.zip" -o ffmpeg-shared.zip
          unzip ffmpeg-shared.zip
          cp ffmpeg-n7.1-latest-win64-gpl-shared/bin/*.dll .
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rtsp_record_windows_x64
          path: |
            rtsp_record.exe
            *.dll
